/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.walmart.dm.datapush.avro.schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeliveryPrefSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryPrefSchema\",\"namespace\":\"com.walmart.dm.datapush.avro.schema\",\"fields\":[{\"name\":\"Id\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"prefix\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"middleName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"},{\"name\":\"suffix\",\"type\":\"string\"},{\"name\":\"jobTitle\",\"type\":\"string\"},{\"name\":\"companyName\",\"type\":\"string\"},{\"name\":\"address1\",\"type\":\"string\"},{\"name\":\"address2\",\"type\":\"string\"},{\"name\":\"address3\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"state\",\"type\":\"string\"},{\"name\":\"postalCode\",\"type\":\"string\"},{\"name\":\"county\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"phoneNumber\",\"type\":\"string\"},{\"name\":\"faxNumber\",\"type\":\"string\"},{\"name\":\"etlCreatedDate\",\"type\":\"string\",\"java-class\":\"java.util.Date\"},{\"name\":\"etlModifiedDate\",\"type\":\"string\",\"java-class\":\"java.util.Date\"}],\"doc:\":\"Schema for ATG Delivery Preference Output\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence Id;
  @Deprecated public java.lang.CharSequence userId;
  @Deprecated public java.lang.CharSequence prefix;
  @Deprecated public java.lang.CharSequence firstName;
  @Deprecated public java.lang.CharSequence middleName;
  @Deprecated public java.lang.CharSequence lastName;
  @Deprecated public java.lang.CharSequence suffix;
  @Deprecated public java.lang.CharSequence jobTitle;
  @Deprecated public java.lang.CharSequence companyName;
  @Deprecated public java.lang.CharSequence address1;
  @Deprecated public java.lang.CharSequence address2;
  @Deprecated public java.lang.CharSequence address3;
  @Deprecated public java.lang.CharSequence city;
  @Deprecated public java.lang.CharSequence state;
  @Deprecated public java.lang.CharSequence postalCode;
  @Deprecated public java.lang.CharSequence county;
  @Deprecated public java.lang.CharSequence country;
  @Deprecated public java.lang.CharSequence phoneNumber;
  @Deprecated public java.lang.CharSequence faxNumber;
  @Deprecated public java.lang.CharSequence etlCreatedDate;
  @Deprecated public java.lang.CharSequence etlModifiedDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DeliveryPrefSchema() {}

  /**
   * All-args constructor.
   */
  public DeliveryPrefSchema(java.lang.CharSequence Id, java.lang.CharSequence userId, java.lang.CharSequence prefix, java.lang.CharSequence firstName, java.lang.CharSequence middleName, java.lang.CharSequence lastName, java.lang.CharSequence suffix, java.lang.CharSequence jobTitle, java.lang.CharSequence companyName, java.lang.CharSequence address1, java.lang.CharSequence address2, java.lang.CharSequence address3, java.lang.CharSequence city, java.lang.CharSequence state, java.lang.CharSequence postalCode, java.lang.CharSequence county, java.lang.CharSequence country, java.lang.CharSequence phoneNumber, java.lang.CharSequence faxNumber, java.lang.CharSequence etlCreatedDate, java.lang.CharSequence etlModifiedDate) {
    this.Id = Id;
    this.userId = userId;
    this.prefix = prefix;
    this.firstName = firstName;
    this.middleName = middleName;
    this.lastName = lastName;
    this.suffix = suffix;
    this.jobTitle = jobTitle;
    this.companyName = companyName;
    this.address1 = address1;
    this.address2 = address2;
    this.address3 = address3;
    this.city = city;
    this.state = state;
    this.postalCode = postalCode;
    this.county = county;
    this.country = country;
    this.phoneNumber = phoneNumber;
    this.faxNumber = faxNumber;
    this.etlCreatedDate = etlCreatedDate;
    this.etlModifiedDate = etlModifiedDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Id;
    case 1: return userId;
    case 2: return prefix;
    case 3: return firstName;
    case 4: return middleName;
    case 5: return lastName;
    case 6: return suffix;
    case 7: return jobTitle;
    case 8: return companyName;
    case 9: return address1;
    case 10: return address2;
    case 11: return address3;
    case 12: return city;
    case 13: return state;
    case 14: return postalCode;
    case 15: return county;
    case 16: return country;
    case 17: return phoneNumber;
    case 18: return faxNumber;
    case 19: return etlCreatedDate;
    case 20: return etlModifiedDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Id = (java.lang.CharSequence)value$; break;
    case 1: userId = (java.lang.CharSequence)value$; break;
    case 2: prefix = (java.lang.CharSequence)value$; break;
    case 3: firstName = (java.lang.CharSequence)value$; break;
    case 4: middleName = (java.lang.CharSequence)value$; break;
    case 5: lastName = (java.lang.CharSequence)value$; break;
    case 6: suffix = (java.lang.CharSequence)value$; break;
    case 7: jobTitle = (java.lang.CharSequence)value$; break;
    case 8: companyName = (java.lang.CharSequence)value$; break;
    case 9: address1 = (java.lang.CharSequence)value$; break;
    case 10: address2 = (java.lang.CharSequence)value$; break;
    case 11: address3 = (java.lang.CharSequence)value$; break;
    case 12: city = (java.lang.CharSequence)value$; break;
    case 13: state = (java.lang.CharSequence)value$; break;
    case 14: postalCode = (java.lang.CharSequence)value$; break;
    case 15: county = (java.lang.CharSequence)value$; break;
    case 16: country = (java.lang.CharSequence)value$; break;
    case 17: phoneNumber = (java.lang.CharSequence)value$; break;
    case 18: faxNumber = (java.lang.CharSequence)value$; break;
    case 19: etlCreatedDate = (java.lang.CharSequence)value$; break;
    case 20: etlModifiedDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Id' field.
   */
  public java.lang.CharSequence getId() {
    return Id;
  }

  /**
   * Sets the value of the 'Id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.Id = value;
  }

  /**
   * Gets the value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'prefix' field.
   */
  public java.lang.CharSequence getPrefix() {
    return prefix;
  }

  /**
   * Sets the value of the 'prefix' field.
   * @param value the value to set.
   */
  public void setPrefix(java.lang.CharSequence value) {
    this.prefix = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }

  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'middleName' field.
   */
  public java.lang.CharSequence getMiddleName() {
    return middleName;
  }

  /**
   * Sets the value of the 'middleName' field.
   * @param value the value to set.
   */
  public void setMiddleName(java.lang.CharSequence value) {
    this.middleName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }

  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'suffix' field.
   */
  public java.lang.CharSequence getSuffix() {
    return suffix;
  }

  /**
   * Sets the value of the 'suffix' field.
   * @param value the value to set.
   */
  public void setSuffix(java.lang.CharSequence value) {
    this.suffix = value;
  }

  /**
   * Gets the value of the 'jobTitle' field.
   */
  public java.lang.CharSequence getJobTitle() {
    return jobTitle;
  }

  /**
   * Sets the value of the 'jobTitle' field.
   * @param value the value to set.
   */
  public void setJobTitle(java.lang.CharSequence value) {
    this.jobTitle = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   */
  public java.lang.CharSequence getCompanyName() {
    return companyName;
  }

  /**
   * Sets the value of the 'companyName' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.companyName = value;
  }

  /**
   * Gets the value of the 'address1' field.
   */
  public java.lang.CharSequence getAddress1() {
    return address1;
  }

  /**
   * Sets the value of the 'address1' field.
   * @param value the value to set.
   */
  public void setAddress1(java.lang.CharSequence value) {
    this.address1 = value;
  }

  /**
   * Gets the value of the 'address2' field.
   */
  public java.lang.CharSequence getAddress2() {
    return address2;
  }

  /**
   * Sets the value of the 'address2' field.
   * @param value the value to set.
   */
  public void setAddress2(java.lang.CharSequence value) {
    this.address2 = value;
  }

  /**
   * Gets the value of the 'address3' field.
   */
  public java.lang.CharSequence getAddress3() {
    return address3;
  }

  /**
   * Sets the value of the 'address3' field.
   * @param value the value to set.
   */
  public void setAddress3(java.lang.CharSequence value) {
    this.address3 = value;
  }

  /**
   * Gets the value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'postalCode' field.
   */
  public java.lang.CharSequence getPostalCode() {
    return postalCode;
  }

  /**
   * Sets the value of the 'postalCode' field.
   * @param value the value to set.
   */
  public void setPostalCode(java.lang.CharSequence value) {
    this.postalCode = value;
  }

  /**
   * Gets the value of the 'county' field.
   */
  public java.lang.CharSequence getCounty() {
    return county;
  }

  /**
   * Sets the value of the 'county' field.
   * @param value the value to set.
   */
  public void setCounty(java.lang.CharSequence value) {
    this.county = value;
  }

  /**
   * Gets the value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }

  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phoneNumber;
  }

  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'faxNumber' field.
   */
  public java.lang.CharSequence getFaxNumber() {
    return faxNumber;
  }

  /**
   * Sets the value of the 'faxNumber' field.
   * @param value the value to set.
   */
  public void setFaxNumber(java.lang.CharSequence value) {
    this.faxNumber = value;
  }

  /**
   * Gets the value of the 'etlCreatedDate' field.
   */
  public java.lang.CharSequence getEtlCreatedDate() {
    return etlCreatedDate;
  }

  /**
   * Sets the value of the 'etlCreatedDate' field.
   * @param value the value to set.
   */
  public void setEtlCreatedDate(java.lang.CharSequence value) {
    this.etlCreatedDate = value;
  }

  /**
   * Gets the value of the 'etlModifiedDate' field.
   */
  public java.lang.CharSequence getEtlModifiedDate() {
    return etlModifiedDate;
  }

  /**
   * Sets the value of the 'etlModifiedDate' field.
   * @param value the value to set.
   */
  public void setEtlModifiedDate(java.lang.CharSequence value) {
    this.etlModifiedDate = value;
  }

  /** Creates a new DeliveryPrefSchema RecordBuilder */
  public static com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder newBuilder() {
    return new com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder();
  }
  
  /** Creates a new DeliveryPrefSchema RecordBuilder by copying an existing Builder */
  public static com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder newBuilder(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder other) {
    return new com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder(other);
  }
  
  /** Creates a new DeliveryPrefSchema RecordBuilder by copying an existing DeliveryPrefSchema instance */
  public static com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder newBuilder(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema other) {
    return new com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder(other);
  }
  
  /**
   * RecordBuilder for DeliveryPrefSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryPrefSchema>
    implements org.apache.avro.data.RecordBuilder<DeliveryPrefSchema> {

    private java.lang.CharSequence Id;
    private java.lang.CharSequence userId;
    private java.lang.CharSequence prefix;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence middleName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence suffix;
    private java.lang.CharSequence jobTitle;
    private java.lang.CharSequence companyName;
    private java.lang.CharSequence address1;
    private java.lang.CharSequence address2;
    private java.lang.CharSequence address3;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state;
    private java.lang.CharSequence postalCode;
    private java.lang.CharSequence county;
    private java.lang.CharSequence country;
    private java.lang.CharSequence phoneNumber;
    private java.lang.CharSequence faxNumber;
    private java.lang.CharSequence etlCreatedDate;
    private java.lang.CharSequence etlModifiedDate;

    /** Creates a new Builder */
    private Builder() {
      super(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.prefix)) {
        this.prefix = data().deepCopy(fields()[2].schema(), other.prefix);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.middleName)) {
        this.middleName = data().deepCopy(fields()[4].schema(), other.middleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lastName)) {
        this.lastName = data().deepCopy(fields()[5].schema(), other.lastName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.suffix)) {
        this.suffix = data().deepCopy(fields()[6].schema(), other.suffix);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.jobTitle)) {
        this.jobTitle = data().deepCopy(fields()[7].schema(), other.jobTitle);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.companyName)) {
        this.companyName = data().deepCopy(fields()[8].schema(), other.companyName);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address1)) {
        this.address1 = data().deepCopy(fields()[9].schema(), other.address1);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.address2)) {
        this.address2 = data().deepCopy(fields()[10].schema(), other.address2);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.address3)) {
        this.address3 = data().deepCopy(fields()[11].schema(), other.address3);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.city)) {
        this.city = data().deepCopy(fields()[12].schema(), other.city);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.state)) {
        this.state = data().deepCopy(fields()[13].schema(), other.state);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[14].schema(), other.postalCode);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.county)) {
        this.county = data().deepCopy(fields()[15].schema(), other.county);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.country)) {
        this.country = data().deepCopy(fields()[16].schema(), other.country);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[17].schema(), other.phoneNumber);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.faxNumber)) {
        this.faxNumber = data().deepCopy(fields()[18].schema(), other.faxNumber);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.etlCreatedDate)) {
        this.etlCreatedDate = data().deepCopy(fields()[19].schema(), other.etlCreatedDate);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.etlModifiedDate)) {
        this.etlModifiedDate = data().deepCopy(fields()[20].schema(), other.etlModifiedDate);
        fieldSetFlags()[20] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DeliveryPrefSchema instance */
    private Builder(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema other) {
            super(com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.SCHEMA$);
      if (isValidValue(fields()[0], other.Id)) {
        this.Id = data().deepCopy(fields()[0].schema(), other.Id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userId)) {
        this.userId = data().deepCopy(fields()[1].schema(), other.userId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.prefix)) {
        this.prefix = data().deepCopy(fields()[2].schema(), other.prefix);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.middleName)) {
        this.middleName = data().deepCopy(fields()[4].schema(), other.middleName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lastName)) {
        this.lastName = data().deepCopy(fields()[5].schema(), other.lastName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.suffix)) {
        this.suffix = data().deepCopy(fields()[6].schema(), other.suffix);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.jobTitle)) {
        this.jobTitle = data().deepCopy(fields()[7].schema(), other.jobTitle);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.companyName)) {
        this.companyName = data().deepCopy(fields()[8].schema(), other.companyName);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.address1)) {
        this.address1 = data().deepCopy(fields()[9].schema(), other.address1);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.address2)) {
        this.address2 = data().deepCopy(fields()[10].schema(), other.address2);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.address3)) {
        this.address3 = data().deepCopy(fields()[11].schema(), other.address3);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.city)) {
        this.city = data().deepCopy(fields()[12].schema(), other.city);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.state)) {
        this.state = data().deepCopy(fields()[13].schema(), other.state);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[14].schema(), other.postalCode);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.county)) {
        this.county = data().deepCopy(fields()[15].schema(), other.county);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.country)) {
        this.country = data().deepCopy(fields()[16].schema(), other.country);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[17].schema(), other.phoneNumber);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.faxNumber)) {
        this.faxNumber = data().deepCopy(fields()[18].schema(), other.faxNumber);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.etlCreatedDate)) {
        this.etlCreatedDate = data().deepCopy(fields()[19].schema(), other.etlCreatedDate);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.etlModifiedDate)) {
        this.etlModifiedDate = data().deepCopy(fields()[20].schema(), other.etlModifiedDate);
        fieldSetFlags()[20] = true;
      }
    }

    /** Gets the value of the 'Id' field */
    public java.lang.CharSequence getId() {
      return Id;
    }
    
    /** Sets the value of the 'Id' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'Id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'Id' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearId() {
      Id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'userId' field */
    public java.lang.CharSequence getUserId() {
      return userId;
    }
    
    /** Sets the value of the 'userId' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.userId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'userId' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'userId' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'prefix' field */
    public java.lang.CharSequence getPrefix() {
      return prefix;
    }
    
    /** Sets the value of the 'prefix' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setPrefix(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.prefix = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'prefix' field has been set */
    public boolean hasPrefix() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'prefix' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearPrefix() {
      prefix = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'firstName' field */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }
    
    /** Sets the value of the 'firstName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.firstName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'firstName' field has been set */
    public boolean hasFirstName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'firstName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'middleName' field */
    public java.lang.CharSequence getMiddleName() {
      return middleName;
    }
    
    /** Sets the value of the 'middleName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setMiddleName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.middleName = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'middleName' field has been set */
    public boolean hasMiddleName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'middleName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearMiddleName() {
      middleName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'lastName' field */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }
    
    /** Sets the value of the 'lastName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.lastName = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'lastName' field has been set */
    public boolean hasLastName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'lastName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'suffix' field */
    public java.lang.CharSequence getSuffix() {
      return suffix;
    }
    
    /** Sets the value of the 'suffix' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setSuffix(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.suffix = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'suffix' field has been set */
    public boolean hasSuffix() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'suffix' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearSuffix() {
      suffix = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'jobTitle' field */
    public java.lang.CharSequence getJobTitle() {
      return jobTitle;
    }
    
    /** Sets the value of the 'jobTitle' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setJobTitle(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.jobTitle = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'jobTitle' field has been set */
    public boolean hasJobTitle() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'jobTitle' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearJobTitle() {
      jobTitle = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'companyName' field */
    public java.lang.CharSequence getCompanyName() {
      return companyName;
    }
    
    /** Sets the value of the 'companyName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.companyName = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'companyName' field has been set */
    public boolean hasCompanyName() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'companyName' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'address1' field */
    public java.lang.CharSequence getAddress1() {
      return address1;
    }
    
    /** Sets the value of the 'address1' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setAddress1(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.address1 = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'address1' field has been set */
    public boolean hasAddress1() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'address1' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearAddress1() {
      address1 = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'address2' field */
    public java.lang.CharSequence getAddress2() {
      return address2;
    }
    
    /** Sets the value of the 'address2' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setAddress2(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.address2 = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'address2' field has been set */
    public boolean hasAddress2() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'address2' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearAddress2() {
      address2 = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'address3' field */
    public java.lang.CharSequence getAddress3() {
      return address3;
    }
    
    /** Sets the value of the 'address3' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setAddress3(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.address3 = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'address3' field has been set */
    public boolean hasAddress3() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'address3' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearAddress3() {
      address3 = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'city' field */
    public java.lang.CharSequence getCity() {
      return city;
    }
    
    /** Sets the value of the 'city' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.city = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'city' field has been set */
    public boolean hasCity() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'city' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearCity() {
      city = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'state' field */
    public java.lang.CharSequence getState() {
      return state;
    }
    
    /** Sets the value of the 'state' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setState(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.state = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'state' field has been set */
    public boolean hasState() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'state' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearState() {
      state = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'postalCode' field */
    public java.lang.CharSequence getPostalCode() {
      return postalCode;
    }
    
    /** Sets the value of the 'postalCode' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setPostalCode(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.postalCode = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'postalCode' field has been set */
    public boolean hasPostalCode() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'postalCode' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearPostalCode() {
      postalCode = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'county' field */
    public java.lang.CharSequence getCounty() {
      return county;
    }
    
    /** Sets the value of the 'county' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setCounty(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.county = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'county' field has been set */
    public boolean hasCounty() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'county' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearCounty() {
      county = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'country' field */
    public java.lang.CharSequence getCountry() {
      return country;
    }
    
    /** Sets the value of the 'country' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.country = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'country' field has been set */
    public boolean hasCountry() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'country' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearCountry() {
      country = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'phoneNumber' field */
    public java.lang.CharSequence getPhoneNumber() {
      return phoneNumber;
    }
    
    /** Sets the value of the 'phoneNumber' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.phoneNumber = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'phoneNumber' field has been set */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'phoneNumber' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'faxNumber' field */
    public java.lang.CharSequence getFaxNumber() {
      return faxNumber;
    }
    
    /** Sets the value of the 'faxNumber' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setFaxNumber(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.faxNumber = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'faxNumber' field has been set */
    public boolean hasFaxNumber() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'faxNumber' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearFaxNumber() {
      faxNumber = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'etlCreatedDate' field */
    public java.lang.CharSequence getEtlCreatedDate() {
      return etlCreatedDate;
    }
    
    /** Sets the value of the 'etlCreatedDate' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setEtlCreatedDate(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.etlCreatedDate = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'etlCreatedDate' field has been set */
    public boolean hasEtlCreatedDate() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'etlCreatedDate' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearEtlCreatedDate() {
      etlCreatedDate = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'etlModifiedDate' field */
    public java.lang.CharSequence getEtlModifiedDate() {
      return etlModifiedDate;
    }
    
    /** Sets the value of the 'etlModifiedDate' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder setEtlModifiedDate(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.etlModifiedDate = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'etlModifiedDate' field has been set */
    public boolean hasEtlModifiedDate() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'etlModifiedDate' field */
    public com.walmart.dm.datapush.avro.schema.DeliveryPrefSchema.Builder clearEtlModifiedDate() {
      etlModifiedDate = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    @Override
    public DeliveryPrefSchema build() {
      try {
        DeliveryPrefSchema record = new DeliveryPrefSchema();
        record.Id = fieldSetFlags()[0] ? this.Id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userId = fieldSetFlags()[1] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.prefix = fieldSetFlags()[2] ? this.prefix : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.firstName = fieldSetFlags()[3] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.middleName = fieldSetFlags()[4] ? this.middleName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.lastName = fieldSetFlags()[5] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.suffix = fieldSetFlags()[6] ? this.suffix : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.jobTitle = fieldSetFlags()[7] ? this.jobTitle : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.companyName = fieldSetFlags()[8] ? this.companyName : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.address1 = fieldSetFlags()[9] ? this.address1 : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.address2 = fieldSetFlags()[10] ? this.address2 : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.address3 = fieldSetFlags()[11] ? this.address3 : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.city = fieldSetFlags()[12] ? this.city : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.state = fieldSetFlags()[13] ? this.state : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.postalCode = fieldSetFlags()[14] ? this.postalCode : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.county = fieldSetFlags()[15] ? this.county : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.country = fieldSetFlags()[16] ? this.country : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.phoneNumber = fieldSetFlags()[17] ? this.phoneNumber : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.faxNumber = fieldSetFlags()[18] ? this.faxNumber : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.etlCreatedDate = fieldSetFlags()[19] ? this.etlCreatedDate : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.etlModifiedDate = fieldSetFlags()[20] ? this.etlModifiedDate : (java.lang.CharSequence) defaultValue(fields()[20]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
